apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kernel-module-management-must-gather
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/kernel-module-management/kernel-module-management-must-gather@sha256:7250018f16c5a9bed207a5e4c66934961bbfb2850c289a0e7e48879023c30a6f
        name: container-image
        resources: {}
status: {}
