apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kernel-module-management-must-gather
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/kernel-module-management/kernel-module-management-must-gather@sha256:e04884795ba66a16465d54c4f1af8d3f9fc45c8fb60411fe5a571238485102d8
        name: container-image
        resources: {}
status: {}
