apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kernel-module-management
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/kernel-module-management/kernel-module-management@sha256:8a31e10e4192b02668edf6393ba08e1c9a9f28fb796f7a8e79dff2749ca83203
        name: container-image
        resources: {}
status: {}
