apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kernel-module-management
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/kernel-module-management/kernel-module-management@sha256:104e7589b20e26d802a4194935d2dc9bb4e939fe7633702f6ed09107fb06feb7
        name: container-image
        resources: {}
status: {}
