apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kernel-module-management
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/kernel-module-management/kernel-module-management@sha256:9c49a71cfca882fa777256f9936990a49406703e088ed9b563dc95388d2cdead
        name: container-image
        resources: {}
status: {}
