apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kernel-module-management-must-gather
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kernel-module-management-must-gather
    app.kubernetes.io/part-of: kernel-module-management
  name: kernel-module-management-must-gather
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kernel-module-management-must-gather
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kernel-module-management-must-gather
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/kernel-module-management/kernel-module-management-must-gather@sha256:c546a8aff7ca3ea750734ccfc65228986457f4f8124e9b8693a85e76115e2210
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
